# Generated by Django 4.2.11 on 2024-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolment',
            field=models.ManyToManyField(to='stdreg.course'),
        ),
    ]
