# Generated by Django 4.2.11 on 2024-06-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_code', models.CharField(max_length=30)),
                ('meeting_dt', models.DateField(auto_now_add=True)),
                ('meeting_subject', models.CharField(max_length=100)),
                ('meeting_np', models.IntegerField()),
            ],
        ),
    ]
